version: '3'

services:

  zspotify:
    image: jsavargas/zspotify
    container_name: zspotify
    restart: unless-stopped
    network_mode: bridge
    environment:
      - 'PUID=99'
      - 'PGID=100'
      - 'TZ=America/Santiago'
      - LIMIT_ELEMENTS=50       #Optional
    volumes:
      - /mnt/user/appdata/zspotify:/root/.config/ZSpotify
      - /mnt/user/download/torrent:/root/Music/
